name: Build and Test

on: [pull_request]

# Add permissions for github-script to comment on PRs
permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  build:
    name: Build and Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PNPM
        run: corepack enable && pnpm -v

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.19.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build Integration Package
        run: pnpm --filter astro-prometheus-node-integration build

      - name: Run Unit Tests
        run: pnpm --filter astro-prometheus-node-integration test -- --run

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 15
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PNPM
        run: corepack enable && pnpm -v

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.19.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Integration Package
        run: |
          cd packages/astro-prometheus-node-integration
          pnpm build

      - name: Build Playground
        run: |
          cd playground
          pnpm build

      - name: Install Playwright Chromium
        run: |
          cd playground
          npx playwright install chromium --with-deps

      - name: Run E2E Tests
        run: |
          cd playground
          npm run test:e2e -- --reporter=line
        env:
          CI: true

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playground/test-results/
          retention-days: 30

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playground/playwright-report/
          retention-days: 30

      - name: Comment PR with Test Results
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            try {
              const testResultsPath = 'playground/test-results/';
              if (fs.existsSync(testResultsPath)) {
                const files = fs.readdirSync(testResultsPath);
                const hasFailures = files.some(file => file.includes('failed'));
                
                if (hasFailures) {
                  github.rest.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: `❌ **E2E Tests Failed**\n\nSome end-to-end tests failed. Check the [workflow run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.\n\n**Test artifacts are available for download above.**`
                  });
                } else {
                  github.rest.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: `✅ **E2E Tests Passed**\n\nAll end-to-end tests passed successfully! The Astro Prometheus integration is working correctly.\n\n**Test artifacts are available for download above.**`
                  });
                }
              }
            } catch (error) {
              console.log('Could not read test results:', error.message);
            }
